[project]
name = "tf3-localization-zh-hk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chungchungdev", email = "chungchung.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
tf3-localization-zh-hk = "tf3_localization_zh_hk:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
